### ISSUE TITLE
WebAssembly

### ISSUE THREAD

**Issue by flip111** [Nukleus-Language/nukleus#10]
Does the compiler run on WebAssembly (wasm)? Is such feature planned?

**Comment by SkuldNorniern** [comment]
Hi
Sorry for the late response.

I appreciate your interest in the Nukleus language and its potential integration with WebAssembly (wasm). 

While the current version of the Nukleus compiler **does not** support WebAssembly.
I'm currently exploring a bifurcated approach. This would involve creating two distinct versions of Nukleus or a brand new one tailored for WebAssembly with a more flexible syntax, while Nukleus itself maintains our traditional, strict syntax grammar.

 and there are still some possibilities of just integrating the feature into Nukleus.

**Comment by flip111** [comment]
Thank you for your reply. Close the issue if you like or keep it open in case you like a reminder.

**Comment by SkuldNorniern** [comment]
https://github.com/orgs/Nukleus-Language/projects/1?pane=issue&itemId=51553741

Milestone added
