### ISSUE TITLE
fix: `return` statement doesn't work inside `if` block

### ISSUE THREAD

**Issue by ybs1164** [Nukleus-Language/nukleus#5]
```rs
fn main() -> void {
    let:i32 x = 3;

    if (x < 5) {
        println("yeah");
        return;
    }

    println("out that");
    return;
}
```

error message like this

```thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ExpectedOther { token: "}" }', src\main.rs:74:25 note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace```

**Comment by SkuldNorniern** [comment]
Will be fixed on Nightly build 2023-04 B2 (Hopely)
Currently working on tracing the Function scoop for the statement
